name: push-image
on:
  push:
    branches:
      - master

jobs:
  dockerhub-push-commit-hash:
    name: push image to DockerHub with commit hash tag
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: amasuda/plantuml-cli
          registry: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  dockerhub-push-latest:
    name: push image to DockerHub with latest tag
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: amasuda/plantuml-cli
          tag: latest
          registry: hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}