name: update-image
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron:  '10 9 * * *'
env:
  TZ: "Asia/Tokyo"

jobs:
  update-image:
    name: update image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check package update
        run: make update
      - id: check-update
        name: check if Dockerfile update required
        run: |
          if git diff-index --quiet HEAD --; then
            echo "git diff exit code $?. No changes"
            echo ::set-output name=update::false
          else
            echo "git diff exit code $?. Update detected"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add --all
            git commit -m "[GitHub Action] Update automatically"
            echo ::set-output name=update::true
          fi
      - name: push if updated
        if: steps.check-update.outputs.update == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
